### ISSUE TITLE
Start releasing the NoChangeLogLock extension again

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase-nochangeloglock#32]
## Description

The nochangeloglock extension hasn't been released since 2014, but if anything it's more needed than ever since external orchestration tools like kubernetes can do a better job of managing concurrency natively than the databasechangeloglock table can.

## Things to do:

1. Bring in our standard build and release process logic to this extension
2. Update the pom to be using current liquibase-core
3. Test that the extension still works with the current liquibase-core
4. Update the liquibase release logic to include publishing this extension as well with on each liquibase release

**Comment by kevin-atx** [comment]
Discussing this with @nvoxland  - this is becoming more needed as people are using Kubernetes to run Liquibase. The goal of this ticket is to give users the option to remove the Liquibase locking functionality so it can be handled by tools outside of Liquibase.

**Comment by nvoxland** [comment]
I added the github logic to release this, and cleaned up the configuration code to make it better fit with current liquibase capabilities.

4.17.2 has been released and we'll release it going forward now.
